spring:
  application:
    name: spring-hystrix
  profiles:
    active: dev
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

server:
  port: 10001

logging:
  config: classpath:logback-spring.xml
  
