spring:
  application:
    name: spring-hystrix
  profiles:
    active: dev
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

server:
  port: 10002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

logging:
  config: classpath:logback-spring.xml
  
