server:
  port: 8100

eureka:
  instance:
    hostname: eurekaserver
  client:
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false